/*
 *  cppClassTemplate.h
 *  ddl2cpp
 *
 *  C++ class template as strings, intended to be populated
 *  with database fields and accessors, parsed from a DDL (SQLite) description.
 *
 *  Created by Mathias Franck on 02/03/12.
 *  Copyright 2012 Vidal. All rights reserved.
 *
 */

static const wstring hxxPrologue=L"\
/*\n\
*  $className.hxx\n\
*  \n\
*  C++ mapping generated by ddl2cpp (written by Mathias Franck).\n\
*  Copyright 2012 Vidal. All rights reserved.\n\
*\n\
*/\n\n\
#ifndef $className_HXX\n\
#define $className_HXX\n\n\
#include \"mapping-headers.h\"\n\n";

static const wstring hxxClassProplogue=L"\n\
class $className { \n\
public: \n\
	static std::vector<$className> findAll();\n";
static const wstring findByNameDecl=L"\
	static std::vector<$className> findByName(std::string name);\n";
static const wstring findByIdDecl=L"\
	static const $className findById(int id);\n";
static const wstring hxxFields=L"\
private:\n";
static const wstring hxxEpilogue=L"\
};\n\
#endif";

static const wstring requestFindById=L"select * from $table where $primaryKey = ";
static const wstring requestFindById_define=L"REQ_$classUpper_FIND_BY_ID";

static const wstring requestFindAll=L"select * from $table";
static const wstring requestFindAll_define=L"REQ_$classUpper_FIND_ALL";

static const wstring requestManyToMany=L"#define select * from $targetTable inner join $linkTable on $targetTable.$targetKey=$linkTable.$linkTargetKey and $linkTable.$linkedSourceKey=";

static const wstring requestOneToMany=L"#define REQ_$classUpper_LOAD_ALL_$targetRoleUpperS select * from $targetTable where $targetTable.$sourceKey=";//<this.PK>;

static const wstring requestToOne=L"#define REQ_$classUpper_LOAD_$targetRoleUpper select * from $targetTable where $targetKey="; //<this.FK>
