/*
*  Book.h
*  
*  C++ mapping generated by ddl2orm (written by Mathias Franck).
*  Copyleft 2012 Merguez-it.
*
*/

#ifndef Book_H
#define Book_H

#include "lorm.h"

class Borrows;
class Person;

class Book : public table<Book> { 
public: 
  TABLE_INIT(Book,book)
	column<int> id;
	column<std::string> author;
	column<std::string> title;
	reference<Person> owner;
	COLLECTION(Borrows,borrows);
	COLLECTION(Person,borrowers);
	COLLECTION(Person,happy_readers);
};

#endif