/*
*  Borrows.h
*  
*  C++ mapping generated by ddl2orm (written by Mathias Franck).
*  Copyleft 2012 Merguez-it.
*
*/

#ifndef Borrows_H
#define Borrows_H

#include "lorm.h"

class Book;
class Person;

class Borrows : public table<Borrows> { 
public: 
  TABLE_INIT(Borrows,borrows)
	column<int> id;
	column<datetime> date_of_borrow;
	reference<Book> borrowed_book;
	reference<Person> borrower;
};

#endif