/*
*  Person.cpp
*  
*  C++ mapping generated by ddl2orm (written by Mathias Franck).
*  Copyleft 2012 Merguez-it.
*
*/

#include "Person.h"
#include "Book.h"

REGISTER_TABLE(Person) {
	identity("person_id",&Person::id);
	field("name", &Person::name);
};

has_and_belongs_to_many(Person,Book,borrowed_books,"borrows","borrower_id","borrowed_book_id");
has_many(Person,Book,books,owner);
